spring.application.name=shortener
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
Database JDBC URL [jdbc:postgresql://127.0.0.1:64113/mydatabase?ApplicationName=shortener]

ports:
- '5432:5432'
